version: '3'
services:
  daemon:
    image: linuxserver/transmission
    volumes:
      - ${TRANSMISSION_VOLUME_CONFIG:-./volumes/config}:/config
      - ${TRANSMISSION_VOLUME_WATCH:-./volumes/watch}:/watch
      - ${TRANSMISSION_VOLUME_DOWNLOADS:-./volumes/downloads}:/downloads
    environment:
      - USERID=${TRANSMISSION_ID_USER:-0}
      - GROUPID=${TRANSMISSION_ID_GROUP:-0}
      - TZ=${TRANSMISSION_TZ:-CST}
      - TRUSER=${TRANSMISSION_GUI_USER:-transmission}
      - TRPASSWD=${TRANSMISSION_GUI_PASSWD:-changeme}
    ports:
      - ${TRANSMISSION_PORT_HTTP:-9091}:9091
      - ${TRANSMISSION_PORT:-51413}:51413
